name: Update Spanish (es)
on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:
jobs:
  copy:
    name: Copy translations
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Set up Python 3
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Copy translations from es-ES to es
        run: |
          python .github/scripts/copy_locale.py --source es-ES --dest es --path mozilla-mobile/firefox-android
          python .github/scripts/copy_locale.py --source es-ES --dest es --path mozilla-mobile/fenix
      - name: Set up git and commit
        run : |
          git config user.name 'flodolo'
          git config user.email 'flodolo@users.noreply.github.com'
          git add .
          git diff-index --quiet HEAD || git commit -m "Update Spanish (es) localizations"
          git push
